# Generated by Django 3.2.12 on 2022-03-21 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studdetails',
            fields=[
                ('name', models.CharField(max_length=55)),
                ('roll_num', models.IntegerField(primary_key=True, serialize=False)),
                ('DOB', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='studmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('English', models.IntegerField()),
                ('Maths', models.IntegerField()),
                ('History', models.IntegerField()),
                ('roll_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studApp.studdetails')),
            ],
        ),
    ]
